# Generated by Django 3.2.5 on 2021-07-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_auto_20210715_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('S', 'mala'), ('M', 'średnia'), ('L', 'duża'), ('XXL', 'ogromna')], default='S', max_length=30),
        ),
    ]
